config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :heroes do
    resources :reviews, only: [ :new, :create ]
    resources :likes
  end
  resources :reviews, only: [ :destroy ]

  resources :users, except: [ :index, :destroy ]
  resources :publisers, only: [:new, :create]
  resources :contacts, only: [:new, :create]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :heroes, dependent: :destroy, class_name: 'Heroe'
  has_many :reviews
  has_many :likes, dependent: :destroy
  has_one_attached :photo

  validates :email,
  :presence => :true,
  :format => {
    :with => /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i,
    :message => "email not valid"
  }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  #validates :first_name, :last_name, :email, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook, :github, :google_oauth2]

  after_create :send_welcome_email
  after_create :subscribe_to_newsletter

  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice("provider", "uid")
    user_params.merge! auth.info.slice("email", "first_name", "last_name")
    # user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h
    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end
    return user
  end

  # def self.from_omniauth(auth)
  #   where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
  #     user.email = auth.info.email
  #     user.token = auth.credentials.token
  #     user.token_expiry = Time.at(auth.credentials.expires_at)
  #     user.password = Devise.friendly_token[0, 20]
  #     user.username = auth.info.name   # assuming the user model has a name
  #     user.photo = auth.info.image # assuming the user model has an image
  #     # If you are using confirmable and the provider(s) you use validate emails,
  #     # uncomment the line below to skip the confirmation emails.
  #     # user.skip_confirmation!
  #   end
  # end

  def self.create_from_provider_data(provider_data)
    where(provider: provider_data.provider, uid: provider_data.uid).first_or_create do |user|
      if provider_data.provider == "google_oauth2"
        user.first_name = provider_data.info.first_name
        user.last_name = provider_data.info.last_name
        user.username = provider_data.info.first_name
      else
        user.first_name = provider_data.info.name.split[0]
        user.last_name = provider_data.info.name.split[1]
        user.username = provider_data.info.nickname
      end
      user.email = provider_data.info.email
      user.token = provider_data.credentials.token
      user.password = Devise.friendly_token[0, 20]
    end
  end


  # def self.new_with_session(params, session)
  #   super.tap do |user|
  #     if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
  #       user.email = data["email"] if user.email.blank?
  #     end
  #   end
  # end

  private



  def subscribe_to_newsletter
    SubscribeToNewsletterService.new(self).call
  end

  def send_welcome_email
    UserMailer.with(user: self).welcome.deliver
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # def facebook
  #   @user = User.create_from_provider_data(request.env["omniauth.auth"])
  #   if @user.persisted?
  #     sign_in_and_redirect @user #this will throw if @user is not activated
  #     set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
  #   else
  #     session["devise.facebook_data"] = request.env["omniauth.auth"]
  #     flash[:error] = 'There was a problem signing you in through Facebook. Please register or try signing later'
  #     redirect_to new_user_registration_url
  #   end
  # end

 def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])
    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  def github
    @user = User.create_from_provider_data(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Github") if is_navigational_format?
    else
      session["devise.github_data"] = request.env["omniauth.auth"]
      flash[:error] = 'There was a problem signing you in through Github. Please register or try signing later'
      redirect_to new_user_registration_url
    end
  end

  def google_oauth2
    @user = User.create_from_provider_data(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Google") if is_navigational_format?
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      flash[:error] = 'There was a problem signing you in through Google. Please register or try signing later'
      redirect_to new_user_registration_url
    end
  end

  def failure
    flash[:error] = 'There was a problem signing you. Please register or try signing later'
    redirect_to root_path
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    authorize @user
  end

  def edit
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update(user_params)
      flash[:alert] = "Your profile has been successfully updated"
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :username, :last_name, :first_name, :photo)
  end
end

app/views/users/edit.html.erb
<div class="container">
  <div class="row" style="margin-top: 90px;">
    <div class="col-12">
      <h1 class="my-3"><%= @user.username %></h1>

        <div class="bg-white p-3 my-3" id="about-me">
          <div class="d-flex justify-content-between align-items-baseline">
            <h2 class="mb-3">About me</h2>
            <% unless current_page?(edit_user_url) %>
              <span class="btn btn-secondary p-2"><%= link_to "Edit my profile", edit_user_url, id:"btn-edit-profile" %></span>
            <% end %>
          </div>
          <% if current_page?(edit_user_url) %>
            <%= simple_form_for(@user) do |f| %>
              <div class="mb-3">
                <span class="badge badge-primary">Email</span> <span class="text-muted"><%= @user.email %></span>
              </div>
              <%= f.input :username %>
              <%= f.input :first_name %>
              <%= f.input :last_name %>
              <%= f.input :photo, as: :file, class: 'avatar' %>
              <%= f.button :submit, "Update my profile", class: 'btn btn-primary mt-2' %>
            <% end %>
          <% else %>
            <div>
              <ul class="list-unstyled">
                <li class="d-flex align-items-center"><i class="fas fa-user icon-user-profile"></i><%= @user.username %></li>
                <li class="d-flex align-items-center"><i class="far fa-envelope icon-user-profile"></i><%= @user.email %></li>
                <li class="d-flex align-items-center"><i class="far fa-id-badge icon-user-profile"></i><%= "#{@user.first_name} #{@user.last_name}" %></li>
              </ul>
            </div>
          <% end %>
        </div>

    </div>
  </div>
</div>

app/views/users/show.html.erb
  <div class="container">
  <div class="row">
    <div class="col-12">
      <h1 class="highlight my-3 p-3 text-center"><%= @user.username %></h1>
        <div class="bg-white p-3 my-3" id="about-me">
          <div class="d-flex justify-content-between align-items-baseline">
            <h2 class="mb-3">About me</h2>
            <% unless current_page?(edit_user_url) %>
              <span class="btn btn-secondary p-2"><%= link_to "Edit my profile", edit_user_url, id:"btn-edit-profile" %></span>
            <% end %>
          </div>
          <% if current_page?(edit_user_url) %>
            <%= simple_form_for(@user) do |f| %>
              <div class="mb-3">
                <span class="badge badge-primary">Email</span> <span class="text-muted"><%= @user.email %></span>
              </div>
              <%= f.input :first_name %>
              <%= f.input :last_name %>
              <%= f.input :photo, as: :file, class: 'avatar'%>
              <%= f.button :submit, "Update my profile", class: 'btn btn-primary' %>
            <% end %>
          <% else %>
            <div>
              <ul class="list-unstyled">
                <li class="d-flex align-items-center"> <i class="far fa-envelope icon-user-profile pr-2"> </i> <%= @user.email %> </li>
                <li class="d-flex align-items-center"> <i class="far fa-id-badge icon-user-profile pr-2"> </i> <%= "#{@user.first_name} #{@user.last_name}" %> </li>
              </ul>
            </div>
          <% end %>
        </div>

      <div class="bg-white p-3 my-3">
        <h2 class="mb-3">My heroes</h2>
        <div class="row">
          <div class="col-12">
            <div class="d-flex align-items-baseline flex-wrap">
              <% @user.heroes.each do |heroe| %>
                <div class="col-6 p-3">
                  <%= link_to hero_path(heroe) do %>
                    <% if heroe.photos.attached?  %>
                      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)),
                      url('<%= cl_image_path heroe.photos.first.key, height: 300, width: 400, crop: :fill %>');">
                    <% else %>
                      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)),
                      url(<%=heroe.image_hero%>);">
                    <% end %>
                      <h2><%= heroe.name.capitalize %> </h2>
                      <p><i class="fas fa-heart"></i> <%= heroe.likes.count %></p>
                    </div>
                  <% end %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>

      <div class="bg-white p-3 my-3">
        <h2 class="mb-3">My favorites heroes</h2>
        <div class="row">
          <div class="col-12">
            <div class="d-flex align-items-baseline flex-wrap">
              <% @user.likes.each do |like| %>
                <% heroe = Heroe.find(like.heroe_id)  %>
                <div class="col-6 p-3">
                  <%= link_to hero_path(heroe) do %>
                    <% if heroe.photos.attached?  %>
                      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)),
                      url('<%= cl_image_path heroe.photos.first.key, height: 300, width: 400, crop: :fill %>');">
                    <% else %>
                      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)),
                      url(<%=heroe.image_hero%>);">
                    <% end %>
                      <h2><%= heroe.name.capitalize %> </h2>
                      <p><i class="fas fa-heart"></i> <%= heroe.likes.count %></p>
                    </div>
                  <% end %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>