config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :heroes do
    resources :reviews, only: [ :new, :create ]
    resources :likes
  end
  resources :reviews, only: [ :destroy ]

  resources :users, except: [ :index, :destroy ]
  resources :publisers, only: [:new, :create]
  resources :contacts, only: [:new, :create]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<% if current_page?(root_path) %>
  <div class="footer", style="background:transparent!important;position:absolute;width:100%;bottom:0;">
<% else %>
  <div class="footer">
<% end %>

    <div class="footer-links">
      <a href="https://github.com/olboaz" target="_blank"><i class="fab fa-github"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="https://www.linkedin.com/in/patrice-jaszczynski-66a18023/" target="_blank"><i class="fab fa-linkedin"></i></a>
      <a href="mailto:spalkes04@gmail.com?subject=Demande de contact"><i class="far fa-envelope"></i></a>
      <h6 class="m-0"> <%= link_to 'Contact me', new_contact_path %> </h6>
     <!--  <a href="">Contact me</a> -->
    </div>
    <div class="footer-copyright">
      <i class="fas fa-heart"></i> by PJ
    </div>
  </div>

app/views/shared/_navbar.html.erb
<% if current_page?(root_path) || current_page?(new_contact_path) %>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon" style="background-color:transparent;position:absolute;width:100%">
<% elsif request.path[0..6] == "/heroes" %>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon" style="position:relative;width:100%">
<% elsif request.path == "/users/sign_in" || request.path == "/users/sign_up"%>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon" style="background-color:transparent;position:absolute;width:100%">
<% else %>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon" style="background-color:transparent;position:relative;width:100%">
<% end %>

<%= link_to root_path, class: "navbar-brand" do %>
  <h5 class="m-0"><%= image_tag "superhero.svg" %>
  <% if current_page?(root_path) %>
  <% else %>
    All Heroes
  <% end %></h5>
<% end %>

<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>

<% if current_page?('/') ||  current_page?('/users/sign_in') || current_page?('/users/sign_up')%>
<% else %>
  <div class="form-group mr-auto col-lg-4 col-xs-4">
    <%= form_with url: heroes_path, method: "GET", local: true do |f| %>
      <div class="d-flex">
        <% if params[:name].present? %>
          <%= f.text_field :name, class: "form-control rounded search", id: "HeroName", placeholder: params[:name] %>
        <% else %>
          <%= f.text_field :name, class: "form-control rounded search", id: "HeroName", placeholder: "Search by heroe" %>
        <% end %>
        <button type="submit">
          <%= image_tag "strong.svg", id: "icon-search" %>
        </button>
      </div>
    <% end %>
  </div>
<% end %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, height: 300, width: 400, crop: :fill, class: 'avatar', id: 'navbarDropdown', 'data-toggle': 'dropdown', 'aria-haspopup': 'true', 'aria-expanded': 'false'%>
          <% else %>
            <% avatar_url = current_user.facebook_picture_url || "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTmW2TOtLONqklPyFavLgZ2Mz8NvrDYGA4AcaSMqQ8jD_-OSyCb&usqp=CAU" %>
            <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% end %>

          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Add a Heroe", new_hero_path, class: "dropdown-item" %>
            <%= link_to "My Profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <h6>  <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %></h6>
        </li>
        <li class="nav-item">
          <h6><%= link_to "Log in", new_user_session_path, class: "nav-link" %></h6>
        </li>
      <% end %>
    </ul>
  </div>
</div>