config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :heroes do
    resources :reviews, only: [ :new, :create ]
    resources :likes
  end
  resources :reviews, only: [ :destroy ]

  resources :users, except: [ :index, :destroy ]
  resources :publisers, only: [:new, :create]
  resources :contacts, only: [:new, :create]
end

app/models/heroe.rb
class Heroe < ApplicationRecord
  belongs_to :publisher
  belongs_to :user
  has_many_attached :photos
  has_many :likes, dependent: :destroy
  has_many :reviews, dependent: :destroy

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :name, :description, :address, :height, :weight, presence: true
  validates :name, uniqueness:  true

  def self.list
    list = []
    Heroe.all.each do |heroe|
      list << heroe.name
    end
    return list
  end
end

app/controllers/heroes_controller.rb
class HeroesController < ApplicationController
skip_before_action :authenticate_user!, only: [:index, :show]

def index
  if params[:name]
    sql_query = "name ILIKE :name AND latitude IS NOT NULL AND longitude IS NOT NULL"
    @heroes = policy_scope(Heroe.geocoded).where(sql_query, name: "%#{params[:name]}%").order('name ASC') # renvoit tous les héros geocded
  elsif params[:letter] == "All"
    @heroes = policy_scope(Heroe.geocoded).order('name ASC') # renvoit tous les héros geocoded
  elsif params[:letter] != nil
    @heroes = policy_scope(Heroe.geocoded).order("name ASC").where("name like ?", params[:letter]+"%")
  else
    @heroes = policy_scope(Heroe.geocoded).order("name ASC")
  end

  @markers = @heroes.map do |heroe|
    {
      lat: heroe.latitude,
      lng: heroe.longitude,
      infoWindow: render_to_string(partial: "info_window", locals: { heroe: heroe }),
      image_url: helpers.asset_url('superhero.svg')
    }

  end

  @letter_array = ["All"]
  @heroes_list = Heroe.all
  @heroes_list.each do |heroe|
    @letter_array << heroe.name[0,1]
  end
  @letter_array.uniq!

end

def show
  @heroe = Heroe.find(params[:id])
  authorize @heroe
  @avg = @heroe.reviews.map(&:rating).sum / @heroe.reviews.count.to_f
end

def new
  @heroe = Heroe.new
  authorize @heroe
end

def create
  @heroe = Heroe.new(heroe_params)
  authorize @heroe
  @heroe.user = current_user
    if @heroe.save
      redirect_to hero_path(@heroe)
    else
      render :new
    end
end

def edit
  @heroe = Heroe.find(params[:id])
  authorize @heroe
end

def update
  @heroe = Heroe.find(params[:id])
  authorize @heroe
  @heroe.user = current_user
  @heroe.update(heroe_params)
  if @heroe.save
    redirect_to hero_path(@heroe)
  else
    render :new
  end
end

private

def heroe_params
    params.require(:heroe).permit(:name, :description, :aliases, :gender, :race, :address,
    :height, :weight, :image_hero, :publisher_id,
    :intelligence,
    :strength,
    :speed,
    :durability,
    :power,
    :combat,
     photos: [])
end

end

app/views/heroes/_form_heroe.html.erb
<div class="d-flex align-items-center" style="min-height: calc(100vh - 126px);">
  <div class="container background background-filter" style="width: 800px;padding:0;">
    <div class="row">
      <div class="col-12">

        <h1 class="text-center my-3">Add your Heroe !</h1>
        <%= simple_form_for(@heroe) do |f| %>
          <div class="form-hero">
            <div class="col-6 photos-hero">
              <label for="upload"><span id="preview"></span></label>
              <label for="file-upload" class="custom-file-upload">
              <i class="fas fa-cloud-upload-alt"></i> Charger les photos (max 6)
              </label>
              <%= f.input :photos, as: :file, label: false, input_html: { multiple: true, id: "file-upload",
               :onchange => "handleFiles(files)"} %>
            </div>

            <div class="col-6 form-group">
              <%= f.input :name, placeholder: 'Name', label: false %>
              <%= f.input :aliases, placeholder: 'Aliases', label: false %>
              <%= f.association :publisher %>
              <%= f.input :address, placeholder: 'Address', label: false %>
              <%= f.input :description, placeholder: 'description', label: false %>
            </div>
          </div>

          <hr>

          <div class="form-hero">
            <div class="col-6">
              <h3>Appearance</h3>
              <%= f.input :height, placeholder: 'Height', label: false  %>
              <%= f.input :weight, placeholder: 'Weight', label: false  %>
              <%= f.input :gender, placeholder: 'Gender', label: false  %>
              <%= f.input :race, placeholder: 'Race', label: false  %>
            </div>

            <div class="col-6">
              <h3>Powerstats</h3>
              <%= f.input :intelligence, placeholder: 'Intelligence', label: false  %>
              <%= f.input :strength, placeholder: 'Strength', label: false  %>
              <%= f.input :speed, placeholder: 'Speed', label: false  %>
              <%= f.input :durability, placeholder: 'Durability', label: false  %>
              <%= f.input :power, placeholder: 'Power', label: false  %>
              <%= f.input :combat, placeholder: 'Combat', label: false  %>
            </div>
          </div>
          <div class="mb-3 text-center w-100">
            <%= f.submit class: 'btn btn-lg btn-primary' %>
          </div>
        <% end %>

      </div>
    </div>
  </div>
</div>
<script>
  function handleFiles(files) {
   var imageType = /^image\//;
   for (var i = 0; i < 6; i++) {
   var file = files[i];
   if (!imageType.test(file.type)) {
     alert("veuillez sélectionner une image");
   }else{
     if(i == 0){
       preview.innerHTML = '';
     }
     var img = document.createElement("img");
     img.classList.add("obj");
     img.file = file;
     preview.appendChild(img);
     var reader = new FileReader();
     reader.onload = ( function(aImg) {
     return function(e) {
     aImg.src = e.target.result;
   };
  })(img);

 reader.readAsDataURL(file);
 }
 }
}
</script>

app/views/heroes/_heroe_card.html.erb
<%= link_to heroe_path(heroe) do %>
  <div class="card-heroe">
    <%= image_tag heroe.image_hero %>
    <div class="card-heroe-infos">
      <div>
        <h2><%= heroe.name %></h2>
      </div>
    </div>
  </div>
<% end %>

app/views/heroes/_info_window.html.erb
<%= link_to hero_path(heroe) do %>
    <div class="card-infos" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.9)),
      url('<%= image_path heroe.image_hero%>');">
      <h2 class="card-title"><%= heroe.name.capitalize %> </h2>
      <p class="cm"><i class="fas fa-ruler-vertical"></i> <%= heroe.height %> cm</p>
      <p class="kg"><i class="fas fa-weight-hanging"></i> <%= heroe.weight %> kg</p>
    </div>
<% end %>

app/views/heroes/edit.html.erb
<%= render 'heroes/form_heroe' %>

app/views/heroes/index.html.erb
<div class="container-fluid">
  <div class="d-flex flex-row mt-2 pl-3 letters">
    <% @letter_array.each do |letter| %>
      <div class="letter">
        <%= link_to letter, :letter => letter %>
      </div>
    <% end %>
    <% if @heroes.count == 0 %>
    <% else %>
      <h4 class="pl-3 m-0 d-flex align-items-center"><%= @heroes.count %> Heroes !</h4>
    <% end %>
  </div>

  <div class="row mt-2 m-1">
    <% if @heroes.empty? %>
      <div class="col-6">
        <h3 class="text-center">Sorry, your hero is not in the website yet, please add him !
          <br> <%= link_to "new", new_hero_path%> </h3>
    <% else %>
      <div class="col-6 cards">

        <% @heroes.each do |heroe| %>
          <div class="category">
            <%= link_to hero_path(heroe) do %>
              <% if heroe.photos.attached?  %>
                <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)),
                url('<%= cl_image_path heroe.photos.first.key, height: 300, width: 400, crop: :fill %>');">
              <% else %>
                <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)),
                url(<%=heroe.image_hero%>);">
              <% end %>
                  <h2><%= heroe.name.capitalize %> </h2>
                  <p><i class="fas fa-heart"></i> <%= heroe.likes.count %></p>
                </div>
            <% end %>
          </div>
        <% end %>
    <% end %>
      </div>

    <div class="col-6 p-2">
      <div id="map"
         style="
         position: sticky;
         width: 100%;
         height: 100vh;
         top:10px;
         box-shadow: 0 0 15px rgba(0,0,0,0.2);
         border-radius:10px;"
         data-markers="<%= @markers.to_json %>"
         data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>

app/views/heroes/new.html.erb
<%= render 'heroes/form_heroe' %>

app/views/heroes/show.html.erb
<div class="container" style="position: relative;
    top: 20px;">
  <div class="card-hero">
    <div class="card-image col-5">
      <% if @heroe.photos.attached?  %>
        <%= cl_image_tag @heroe.photos[0].key %>
      <% else %>
        <%= image_tag @heroe.image_hero %>
      <% end %>
      <hr class="ml-auto mr-auto mb-2">
      <div class="likes d-flex">
        <% if current_user %>
        <% pre_like = @heroe.likes.find { |like| like.user_id == current_user.id} %>
        <% end %>
        <% if pre_like && policy(Like).destroy?%>
          <%= link_to hero_like_path(@heroe, pre_like), method: :delete do %>
            <i class="fas fa-heart"></i>
          <% end %>
        <% else %>
          <%= link_to hero_likes_path(@heroe), method: :post do %>
            <i class="far fa-heart"></i>
          <% end %>
        <% end %>
        <p><%= @heroe.likes.count %> <%= (@heroe.likes.count) == 1 ? 'Like' : 'Likes'%></p>
      </div>
    </div>
    <div class="card-hero-infos">
      <% if @heroe.user == current_user %>
        <%= link_to edit_hero_path do %>
          <i class="fas fa-pencil-alt"></i>
        <% end %>
      <% end %>
      <h2 class="highlight text-center mb-3"> <%= @heroe.name %> </h2>
      <i class="text-secondary"><strong>Alias</strong> <%= @heroe.aliases %></i>
      <p class="mb-3 mt-3"><strong><i class="fas fa-map-marked-alt"></i></strong>  <%= @heroe.address %></p>
      <br>
      <div class="d-flex justify-content-between">
        <div class="Appearance">
          <h6>Appearance</h6>
          <p><strong>Gender :</strong> <%= @heroe.gender %> </p>
          <p><strong>Race :</strong>  <%= @heroe.race %></p>

          <% if @heroe.height == 0 %>
            <p><strong>Height :</strong> na </p>
          <% else %>
            <p><strong>Height :</strong> <%= @heroe.height %> cm</p>
          <% end %>

          <% if @heroe.weight == 0 %>
            <p><strong>Weight :</strong> na </p>
          <% else %>
            <p><strong>Weight :</strong> <%= @heroe.weight %> kg</p>
          <% end %>
        </div>

        <div class="powerstats">
          <h6>Powerstats</h6>
          <p><strong>Intelligence :</strong> <%= @heroe.intelligence %> </p>
          <p><strong>Strength :</strong>  <%= @heroe.strength %></p>
          <p><strong>Power :</strong> <%= @heroe.power %> </p>
          <p><strong>Combat :</strong>  <%= @heroe.combat %></p>
          <% if @heroe.speed == 0 %>
            <p><strong>Speed :</strong> na </p>
          <% else %>
            <p><strong>Speed :</strong> <%= @heroe.speed %></p>
          <% end %>

          <% if @heroe.durability == 0 %>
            <p><strong>Durability :</strong> na </p>
          <% else %>
            <p><strong>Durability :</strong> <%= @heroe.durability %></p>
          <% end %>

        </div>
      </div>
      <hr>
      <p><strong>Description :</strong><br><br>
       <%= @heroe.description %></p>
    </div>
  </div>

  <div class="card-reviews mt-3 mb-3 pb-3">
    <div class="container my-3 bg-white">
      <% if @heroe.reviews.any? %>

        <h4 class="p-2" style="position:relative;=">Reviews
          <% if !@avg.nan? || @avg.nil? %>
            <% @avg = (@avg * 2.0).round / 2.0 %>
            <span> <%= icon('fas', 'star', class: 'star-rating') * @avg %></span>
            <% if @avg.round != @avg  %>
              <span><%= icon('fas', 'star-half-alt', class: 'star-rating') %></span>
            <% end %>
            <span><%= icon('far', 'star', class: 'star-rating') * (5 - @avg) %></span>
          <% end %>
          <%= link_to new_hero_review_path(@heroe) do %>
            <!-- <i class="fas fa-feather-alt p-2 m-2"></i> -->
            <i class="far fa-comments with"></i>
          <% end %>
        </h4>



        <% @heroe.reviews.each do |review| %>
          <p class="list-group-item">

            <b> <%= review.user.username.capitalize %></b>

            <% review.rating.to_i.times do  %>
              <span><i class="fas fa-star" style="color:#FFD700;"></i></span>
            <% end %>
            <% review.blank_stars.times do %>
              <span><i class="far fa-star" style="color:#DDDDDD;"></i></span>
            <% end %>

            <% if review.user === current_user %>
            <%= link_to review_path(review),
                    method: :delete,
                    data: { confirm: "Are you sure?" } do %>
                    <i class="fas fa-trash" style="position:absolute;right:15px;color:#CCCCCC;"></i>
                    <% end %>
            <% end %>
             <br>
            <%= review.content %>

          </p>
        <% end %>

      <% else %>
        <h4 class="text-center yellow-color">Please put a comment here !</h4>
        <div class="text-center">
          <%= link_to new_hero_review_path(@heroe) do %>
            <i class="far fa-comments none"></i>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

</div>